# Generated by Django 4.2.5 on 2023-09-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='even_tribe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
