# Generated by Django 4.2.5 on 2023-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_even_tribe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='even_tribe_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
